 
name: Update stats

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 */3 * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN}}
          USERNAME: appledora
          SHOW_TITLE: True
          COMMIT_MESSAGE: wakatime update
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿ 
